// Seed data for the database - self-contained, no browser dependencies
import type { Employee, Task, Project, Meeting, Notice, ChatConversation } from '../src/lib/types'

const now = new Date()
function timeAgo(minutes: number): string {
  return new Date(now.getTime() - minutes * 60000).toISOString()
}
const todayStr = now.toISOString().slice(0, 10)
function future(days: number): string {
  return new Date(now.getTime() + days * 86400000).toISOString().slice(0, 10)
}
function past(days: number): string {
  return new Date(now.getTime() - days * 86400000).toISOString().slice(0, 10)
}

export const employees: Employee[] = [
  { id: 'EMP-001', name: 'Sarah Chen', email: 'sarah.chen@acme.io', role: 'Senior Frontend Engineer', department: 'Engineering', avatar: '/avatars/emp1.jpg', status: 'active', device: 'MacBook Pro 16"', os: 'macOS Sonoma 14.4', ip: '192.168.1.42', location: 'Austin, TX', shiftStart: '09:00', shiftEnd: '17:00', clockIn: '08:52', clockOut: null, activeTimeSec: 24300, idleTimeSec: 1800, awayTimeSec: 600, productivity: 87, lastActivity: timeAgo(1), cpuUsage: 34, ramUsage: 62, diskUsage: 71, battery: 78, online: true, webcamVerified: true, keystrokes: 18420, mouseClicks: 8240, mouseMoves: 42180, screenshotsTaken: 42, apps: [], hourly: [], activities: [], trends: [] },
  { id: 'EMP-002', name: 'Marcus Johnson', email: 'marcus.j@acme.io', role: 'Financial Analyst', department: 'Finance', avatar: '/avatars/emp2.jpg', status: 'meeting', device: 'Dell Latitude 7440', os: 'Windows 11 Pro', ip: '10.0.4.118', location: 'Denver, CO', shiftStart: '08:30', shiftEnd: '17:00', clockIn: '08:24', clockOut: null, activeTimeSec: 26100, idleTimeSec: 2100, awayTimeSec: 1200, productivity: 76, lastActivity: timeAgo(3), cpuUsage: 52, ramUsage: 71, diskUsage: 64, battery: 45, online: true, webcamVerified: true, keystrokes: 12100, mouseClicks: 6420, mouseMoves: 28400, screenshotsTaken: 38, apps: [], hourly: [], activities: [], trends: [] },
  { id: 'EMP-003', name: 'Priya Patel', email: 'priya.patel@acme.io', role: 'UX Designer', department: 'Design', avatar: '/avatars/emp3.jpg', status: 'active', device: 'MacBook Air 15"', os: 'macOS Ventura 13.6', ip: '172.16.8.22', location: 'Seattle, WA', shiftStart: '09:00', shiftEnd: '17:00', clockIn: '09:05', clockOut: null, activeTimeSec: 21600, idleTimeSec: 2700, awayTimeSec: 900, productivity: 91, lastActivity: timeAgo(0), cpuUsage: 28, ramUsage: 54, diskUsage: 48, battery: 92, online: true, webcamVerified: true, keystrokes: 9800, mouseClicks: 12400, mouseMoves: 58200, screenshotsTaken: 51, apps: [], hourly: [], activities: [], trends: [] },
  { id: 'EMP-004', name: 'David Kim', email: 'david.kim@acme.io', role: 'Sales Representative', department: 'Sales', avatar: '/avatars/emp4.jpg', status: 'idle', device: 'HP EliteBook 840', os: 'Windows 11 Pro', ip: '10.0.4.201', location: 'Chicago, IL', shiftStart: '09:00', shiftEnd: '17:00', clockIn: '09:18', clockOut: null, activeTimeSec: 16200, idleTimeSec: 5400, awayTimeSec: 2400, productivity: 58, lastActivity: timeAgo(18), cpuUsage: 12, ramUsage: 43, diskUsage: 55, battery: 22, online: true, webcamVerified: false, keystrokes: 6200, mouseClicks: 3100, mouseMoves: 14200, screenshotsTaken: 24, apps: [], hourly: [], activities: [], trends: [] },
  { id: 'EMP-005', name: 'Elena Rodriguez', email: 'elena.r@acme.io', role: 'Backend Engineer', department: 'Engineering', avatar: '/avatars/emp5.jpg', status: 'active', device: 'MacBook Pro 14"', os: 'macOS Sonoma 14.4', ip: '192.168.1.88', location: 'Remote, CA', shiftStart: '10:00', shiftEnd: '18:00', clockIn: '09:58', clockOut: null, activeTimeSec: 18900, idleTimeSec: 1500, awayTimeSec: 300, productivity: 93, lastActivity: timeAgo(0), cpuUsage: 61, ramUsage: 78, diskUsage: 82, battery: 64, online: true, webcamVerified: true, keystrokes: 22100, mouseClicks: 7800, mouseMoves: 38600, screenshotsTaken: 47, apps: [], hourly: [], activities: [], trends: [] },
  { id: 'EMP-006', name: 'James Wilson', email: 'james.w@acme.io', role: 'Product Manager', department: 'Product', avatar: '/avatars/emp6.jpg', status: 'break', device: 'ThinkPad X1 Carbon', os: 'Ubuntu 22.04 LTS', ip: '10.0.2.55', location: 'Boston, MA', shiftStart: '09:00', shiftEnd: '17:00', clockIn: '08:45', clockOut: null, activeTimeSec: 19800, idleTimeSec: 3600, awayTimeSec: 1800, productivity: 72, lastActivity: timeAgo(12), cpuUsage: 22, ramUsage: 58, diskUsage: 67, battery: 88, online: true, webcamVerified: true, keystrokes: 14200, mouseClicks: 5600, mouseMoves: 24800, screenshotsTaken: 33, apps: [], hourly: [], activities: [], trends: [] },
  { id: 'EMP-007', name: 'Aisha Mohammed', email: 'aisha.m@acme.io', role: 'QA Engineer', department: 'Engineering', avatar: '/avatars/emp1.jpg', status: 'offline', device: 'MacBook Air 13"', os: 'macOS Ventura 13.6', ip: '192.168.1.91', location: 'Atlanta, GA', shiftStart: '09:00', shiftEnd: '17:00', clockIn: '09:02', clockOut: '17:04', activeTimeSec: 27800, idleTimeSec: 2400, awayTimeSec: 800, productivity: 84, lastActivity: timeAgo(640), cpuUsage: 0, ramUsage: 0, diskUsage: 60, battery: 0, online: false, webcamVerified: true, keystrokes: 16800, mouseClicks: 7200, mouseMoves: 31200, screenshotsTaken: 40, apps: [], hourly: [], activities: [], trends: [] },
  { id: 'EMP-008', name: 'Thomas Müller', email: 'thomas.m@acme.io', role: 'DevOps Engineer', department: 'Engineering', avatar: '/avatars/emp2.jpg', status: 'active', device: 'Custom Desktop', os: 'Windows 11 Pro', ip: '10.0.6.14', location: 'Portland, OR', shiftStart: '08:00', shiftEnd: '16:00', clockIn: '07:55', clockOut: null, activeTimeSec: 28800, idleTimeSec: 1200, awayTimeSec: 200, productivity: 89, lastActivity: timeAgo(0), cpuUsage: 47, ramUsage: 83, diskUsage: 91, battery: 100, online: true, webcamVerified: true, keystrokes: 19400, mouseClicks: 6900, mouseMoves: 35400, screenshotsTaken: 55, apps: [], hourly: [], activities: [], trends: [] },
]

export const tasks: Task[] = [
  { id: 'TSK-001', title: 'Implement authentication flow with OAuth 2.0', description: 'Build the complete login/register flow using OAuth 2.0 with PKCE.', type: 'group', assigneeIds: ['EMP-001', 'EMP-005', 'EMP-007'], assigneeNames: ['Sarah Chen', 'Elena Rodriguez', 'Aisha Mohammed'], assigneeAvatars: ['/avatars/emp1.jpg', '/avatars/emp5.jpg', '/avatars/emp1.jpg'], group: 'Backend Squad', projectId: 'PRJ-001', projectName: 'Customer Portal v3', status: 'in-progress', priority: 'high', progress: 65, createdAt: past(1), dueDate: future(4), estimatedHours: 40, loggedHours: 26, tags: ['backend', 'security', 'api'], comments: [{ id: 'c1', author: 'Sarah Chen', avatar: '/avatars/emp1.jpg', text: 'OAuth flow is implemented, working on 2FA now.', timestamp: timeAgo(120) }] },
  { id: 'TSK-002', title: 'Design dashboard wireframes for analytics module', description: 'Create low-fidelity wireframes for the new analytics dashboard.', type: 'individual', assigneeIds: ['EMP-003'], assigneeNames: ['Priya Patel'], assigneeAvatars: ['/avatars/emp3.jpg'], group: null, projectId: 'PRJ-001', projectName: 'Customer Portal v3', status: 'review', priority: 'medium', progress: 90, createdAt: past(2), dueDate: future(1), estimatedHours: 16, loggedHours: 14, tags: ['design', 'ux'], comments: [] },
  { id: 'TSK-003', title: 'Q3 financial reconciliation report', description: 'Complete the Q3 reconciliation between internal ledger and bank statements.', type: 'individual', assigneeIds: ['EMP-002'], assigneeNames: ['Marcus Johnson'], assigneeAvatars: ['/avatars/emp2.jpg'], group: null, projectId: 'PRJ-003', projectName: 'Q3 Financial Close', status: 'in-progress', priority: 'urgent', progress: 45, createdAt: past(3), dueDate: future(2), estimatedHours: 24, loggedHours: 11, tags: ['finance', 'report'], comments: [{ id: 'c4', author: 'Marcus Johnson', avatar: '/avatars/emp2.jpg', text: 'Found 3 discrepancies, investigating.', timestamp: timeAgo(180) }] },
  { id: 'TSK-004', title: 'Set up CI/CD pipeline with automated testing', description: 'Configure GitHub Actions for CI/CD with automated tests.', type: 'group', assigneeIds: ['EMP-008', 'EMP-005'], assigneeNames: ['Thomas Müller', 'Elena Rodriguez'], assigneeAvatars: ['/avatars/emp2.jpg', '/avatars/emp5.jpg'], group: 'DevOps Team', projectId: 'PRJ-002', projectName: 'Platform Infrastructure', status: 'done', priority: 'high', progress: 100, createdAt: past(5), dueDate: past(1), estimatedHours: 32, loggedHours: 34, tags: ['devops', 'ci-cd'], comments: [] },
  { id: 'TSK-005', title: 'Prepare client demo presentation for Acme Corp', description: 'Create a 20-slide deck showcasing the v3 portal features.', type: 'individual', assigneeIds: ['EMP-006'], assigneeNames: ['James Wilson'], assigneeAvatars: ['/avatars/emp6.jpg'], group: null, projectId: 'PRJ-001', projectName: 'Customer Portal v3', status: 'todo', priority: 'medium', progress: 0, createdAt: past(4), dueDate: future(5), estimatedHours: 12, loggedHours: 0, tags: ['product', 'presentation'], comments: [] },
  { id: 'TSK-006', title: 'QA regression test suite for payment module', description: 'Write and execute regression tests for the payment processing module.', type: 'individual', assigneeIds: ['EMP-007'], assigneeNames: ['Aisha Mohammed'], assigneeAvatars: ['/avatars/emp1.jpg'], group: null, projectId: 'PRJ-001', projectName: 'Customer Portal v3', status: 'in-progress', priority: 'high', progress: 55, createdAt: past(3), dueDate: future(3), estimatedHours: 20, loggedHours: 12, tags: ['qa', 'testing'], comments: [] },
  { id: 'TSK-007', title: 'Migrate legacy database to PostgreSQL 16', description: 'Plan and execute the migration of the legacy MySQL database.', type: 'group', assigneeIds: ['EMP-008', 'EMP-005', 'EMP-001'], assigneeNames: ['Thomas Müller', 'Elena Rodriguez', 'Sarah Chen'], assigneeAvatars: ['/avatars/emp2.jpg', '/avatars/emp5.jpg', '/avatars/emp1.jpg'], group: 'Infrastructure Squad', projectId: 'PRJ-002', projectName: 'Platform Infrastructure', status: 'blocked', priority: 'urgent', progress: 30, createdAt: past(5), dueDate: future(7), estimatedHours: 60, loggedHours: 18, tags: ['database', 'migration'], comments: [{ id: 'c7', author: 'Thomas Müller', avatar: '/avatars/emp2.jpg', text: 'Blocked on DBA access credentials.', timestamp: timeAgo(240) }] },
  { id: 'TSK-008', title: 'Update brand guidelines and component library', description: 'Refresh the design system with new brand colors and typography.', type: 'individual', assigneeIds: ['EMP-003'], assigneeNames: ['Priya Patel'], assigneeAvatars: ['/avatars/emp3.jpg'], group: null, projectId: 'PRJ-004', projectName: 'Brand Refresh 2024', status: 'in-progress', priority: 'low', progress: 40, createdAt: past(2), dueDate: future(10), estimatedHours: 30, loggedHours: 12, tags: ['design', 'branding'], comments: [] },
  { id: 'TSK-009', title: 'Sales outreach campaign for Q4 prospects', description: 'Contact 50 warm leads, schedule demos, and update CRM.', type: 'individual', assigneeIds: ['EMP-004'], assigneeNames: ['David Kim'], assigneeAvatars: ['/avatars/emp4.jpg'], group: null, projectId: 'PRJ-005', projectName: 'Q4 Sales Pipeline', status: 'in-progress', priority: 'medium', progress: 25, createdAt: past(4), dueDate: future(14), estimatedHours: 40, loggedHours: 10, tags: ['sales', 'outreach'], comments: [] },
  { id: 'TSK-010', title: 'API rate limiting and request throttling', description: 'Implement rate limiting on all public API endpoints.', type: 'individual', assigneeIds: ['EMP-005'], assigneeNames: ['Elena Rodriguez'], assigneeAvatars: ['/avatars/emp5.jpg'], group: null, projectId: 'PRJ-002', projectName: 'Platform Infrastructure', status: 'review', priority: 'high', progress: 85, createdAt: past(3), dueDate: future(1), estimatedHours: 16, loggedHours: 14, tags: ['backend', 'api'], comments: [] },
]

export const projects: Project[] = [
  { id: 'PRJ-001', name: 'Customer Portal v3', code: 'CPV3', description: 'Complete rebuild of the customer-facing portal with new design system, OAuth auth, and analytics dashboard.', client: 'Internal', department: 'Engineering', status: 'active', progress: 62, startDate: past(5), endDate: future(30), budget: 180000, spent: 112000, teamMembers: ['Sarah Chen', 'Elena Rodriguez', 'Priya Patel', 'Aisha Mohammed', 'James Wilson'], teamAvatars: ['/avatars/emp1.jpg', '/avatars/emp5.jpg', '/avatars/emp3.jpg', '/avatars/emp1.jpg', '/avatars/emp6.jpg'], teamSize: 5, totalTasks: 18, completedTasks: 8, inProgressTasks: 7, blockedTasks: 0, milestones: [{ id: 'm1', title: 'Auth & Security Module', dueDate: past(1), completed: true, progress: 100 }, { id: 'm2', title: 'Analytics Dashboard', dueDate: future(10), completed: false, progress: 65 }, { id: 'm3', title: 'Payment Integration', dueDate: future(20), completed: false, progress: 20 }, { id: 'm4', title: 'Production Launch', dueDate: future(30), completed: false, progress: 0 }], health: 'on-track', priority: 'high' },
  { id: 'PRJ-002', name: 'Platform Infrastructure', code: 'INFRA', description: 'Infrastructure modernization including CI/CD, database migration, API rate limiting, and monitoring stack.', client: 'Internal', department: 'Engineering', status: 'active', progress: 48, startDate: past(5), endDate: future(45), budget: 250000, spent: 138000, teamMembers: ['Thomas Müller', 'Elena Rodriguez', 'Sarah Chen'], teamAvatars: ['/avatars/emp2.jpg', '/avatars/emp5.jpg', '/avatars/emp1.jpg'], teamSize: 3, totalTasks: 22, completedTasks: 9, inProgressTasks: 5, blockedTasks: 3, milestones: [{ id: 'm5', title: 'CI/CD Pipeline', dueDate: past(1), completed: true, progress: 100 }, { id: 'm6', title: 'DB Migration to PostgreSQL 16', dueDate: future(7), completed: false, progress: 30 }, { id: 'm7', title: 'Monitoring & Alerting Stack', dueDate: future(25), completed: false, progress: 15 }, { id: 'm8', title: 'Production Cutover', dueDate: future(45), completed: false, progress: 0 }], health: 'at-risk', priority: 'high' },
  { id: 'PRJ-003', name: 'Q3 Financial Close', code: 'Q3FC', description: 'Complete Q3 financial reconciliation, reporting, and audit preparation.', client: 'Internal', department: 'Finance', status: 'active', progress: 55, startDate: past(3), endDate: future(5), budget: 45000, spent: 26000, teamMembers: ['Marcus Johnson'], teamAvatars: ['/avatars/emp2.jpg'], teamSize: 1, totalTasks: 8, completedTasks: 4, inProgressTasks: 3, blockedTasks: 0, milestones: [{ id: 'm9', title: 'Ledger Reconciliation', dueDate: future(2), completed: false, progress: 45 }, { id: 'm10', title: 'Audit Report Submission', dueDate: future(5), completed: false, progress: 10 }], health: 'on-track', priority: 'medium' },
  { id: 'PRJ-004', name: 'Brand Refresh 2024', code: 'BRND', description: 'Complete brand identity refresh including logo, color system, typography, and component library.', client: 'Internal', department: 'Design', status: 'on-hold', progress: 35, startDate: past(5), endDate: future(60), budget: 80000, spent: 28000, teamMembers: ['Priya Patel'], teamAvatars: ['/avatars/emp3.jpg'], teamSize: 1, totalTasks: 12, completedTasks: 4, inProgressTasks: 3, blockedTasks: 1, milestones: [{ id: 'm11', title: 'Mood Board & Direction', dueDate: past(2), completed: true, progress: 100 }, { id: 'm12', title: 'Component Library v1', dueDate: future(20), completed: false, progress: 40 }, { id: 'm13', title: 'Brand Guidelines Doc', dueDate: future(40), completed: false, progress: 10 }], health: 'on-track', priority: 'low' },
  { id: 'PRJ-005', name: 'Q4 Sales Pipeline', code: 'Q4SP', description: 'Build and convert Q4 sales pipeline through outbound outreach, demos, and proposal generation.', client: 'Internal', department: 'Sales', status: 'active', progress: 28, startDate: past(4), endDate: future(75), budget: 120000, spent: 34000, teamMembers: ['David Kim', 'James Wilson'], teamAvatars: ['/avatars/emp4.jpg', '/avatars/emp6.jpg'], teamSize: 2, totalTasks: 10, completedTasks: 2, inProgressTasks: 5, blockedTasks: 0, milestones: [{ id: 'm14', title: 'Lead List Generation', dueDate: past(1), completed: true, progress: 100 }, { id: 'm15', title: '50 Outreach Demos', dueDate: future(30), completed: false, progress: 25 }, { id: 'm16', title: 'Q4 Target Close', dueDate: future(75), completed: false, progress: 0 }], health: 'on-track', priority: 'medium' },
  { id: 'PRJ-006', name: 'Mobile App MVP', code: 'MOBO', description: 'Build a React Native mobile app MVP with core portal features.', client: 'Internal', department: 'Engineering', status: 'planning', progress: 8, startDate: future(3), endDate: future(90), budget: 200000, spent: 5000, teamMembers: ['Sarah Chen', 'Elena Rodriguez', 'Priya Patel'], teamAvatars: ['/avatars/emp1.jpg', '/avatars/emp5.jpg', '/avatars/emp3.jpg'], teamSize: 3, totalTasks: 6, completedTasks: 0, inProgressTasks: 1, blockedTasks: 0, milestones: [{ id: 'm17', title: 'Tech Stack Selection', dueDate: future(7), completed: false, progress: 40 }, { id: 'm18', title: 'Auth & Navigation', dueDate: future(30), completed: false, progress: 0 }, { id: 'm19', title: 'MVP Release', dueDate: future(90), completed: false, progress: 0 }], health: 'on-track', priority: 'medium' },
]

export const meetings: Meeting[] = [
  { id: 'MTG-001', title: 'Daily Engineering Standup', description: 'Quick daily sync to discuss progress, blockers, and priorities.', organizer: 'James Wilson', organizerAvatar: '/avatars/emp6.jpg', participantIds: ['EMP-001', 'EMP-005', 'EMP-007', 'EMP-008', 'EMP-006'], participantNames: ['Sarah Chen', 'Elena Rodriguez', 'Aisha Mohammed', 'Thomas Müller', 'James Wilson'], participantAvatars: ['/avatars/emp1.jpg', '/avatars/emp5.jpg', '/avatars/emp1.jpg', '/avatars/emp2.jpg', '/avatars/emp6.jpg'], date: todayStr, startTime: '09:00', endTime: '09:15', status: 'completed', platform: 'Google Meet', location: 'Virtual', meetingLink: 'https://meet.google.com/abc-defg-hij', agenda: ['Review yesterday progress', 'Discuss blockers', 'Plan today priorities'], projectName: 'Customer Portal v3', recordingAvailable: true },
  { id: 'MTG-002', title: 'Sprint Planning — Portal v3', description: 'Plan the next 2-week sprint for the Customer Portal v3 project.', organizer: 'James Wilson', organizerAvatar: '/avatars/emp6.jpg', participantIds: ['EMP-001', 'EMP-005', 'EMP-003', 'EMP-007', 'EMP-006'], participantNames: ['Sarah Chen', 'Elena Rodriguez', 'Priya Patel', 'Aisha Mohammed', 'James Wilson'], participantAvatars: ['/avatars/emp1.jpg', '/avatars/emp5.jpg', '/avatars/emp3.jpg', '/avatars/emp1.jpg', '/avatars/emp6.jpg'], date: todayStr, startTime: '14:00', endTime: '15:30', status: 'live', platform: 'Zoom', location: 'Virtual', meetingLink: 'https://zoom.us/j/1234567890', agenda: ['Review sprint goals', 'Groom backlog items', 'Assign story points', 'Identify risks'], projectName: 'Customer Portal v3', recordingAvailable: false },
  { id: 'MTG-003', title: 'Q3 Financial Review with CFO', description: 'Present Q3 financial reconciliation results and audit findings.', organizer: 'Marcus Johnson', organizerAvatar: '/avatars/emp2.jpg', participantIds: ['EMP-002'], participantNames: ['Marcus Johnson'], participantAvatars: ['/avatars/emp2.jpg'], date: todayStr, startTime: '16:00', endTime: '17:00', status: 'scheduled', platform: 'Teams', location: 'Virtual', meetingLink: 'https://teams.microsoft.com/l/meetup-join/abc', agenda: ['Present reconciliation summary', 'Discuss discrepancies', 'Review audit timeline'], projectName: 'Q3 Financial Close', recordingAvailable: false },
  { id: 'MTG-004', title: 'Design Review — Analytics Dashboard', description: 'Review the analytics dashboard wireframes and finalize the component design direction.', organizer: 'Priya Patel', organizerAvatar: '/avatars/emp3.jpg', participantIds: ['EMP-003', 'EMP-001', 'EMP-006'], participantNames: ['Priya Patel', 'Sarah Chen', 'James Wilson'], participantAvatars: ['/avatars/emp3.jpg', '/avatars/emp1.jpg', '/avatars/emp6.jpg'], date: future(1), startTime: '10:00', endTime: '11:00', status: 'scheduled', platform: 'Zoom', location: 'Virtual', meetingLink: 'https://zoom.us/j/9876543210', agenda: ['Review wireframes', 'Discuss data viz components', 'Finalize color system'], projectName: 'Customer Portal v3', recordingAvailable: false },
  { id: 'MTG-005', title: 'Infrastructure Migration Sync', description: 'Sync on the PostgreSQL migration progress and unblock the DBA access issue.', organizer: 'Thomas Müller', organizerAvatar: '/avatars/emp2.jpg', participantIds: ['EMP-008', 'EMP-005', 'EMP-001'], participantNames: ['Thomas Müller', 'Elena Rodriguez', 'Sarah Chen'], participantAvatars: ['/avatars/emp2.jpg', '/avatars/emp5.jpg', '/avatars/emp1.jpg'], date: future(1), startTime: '13:00', endTime: '14:00', status: 'scheduled', platform: 'Google Meet', location: 'Virtual', meetingLink: 'https://meet.google.com/xyz-abcd-efg', agenda: ['Review migration plan', 'Resolve DBA access blocker', 'Set cutover timeline'], projectName: 'Platform Infrastructure', recordingAvailable: false },
  { id: 'MTG-006', title: 'Client Demo — Acme Corp', description: 'Demo the v3 portal features and migration plan to Acme Corp stakeholders.', organizer: 'James Wilson', organizerAvatar: '/avatars/emp6.jpg', participantIds: ['EMP-006', 'EMP-001', 'EMP-003', 'EMP-004'], participantNames: ['James Wilson', 'Sarah Chen', 'Priya Patel', 'David Kim'], participantAvatars: ['/avatars/emp6.jpg', '/avatars/emp1.jpg', '/avatars/emp3.jpg', '/avatars/emp4.jpg'], date: future(2), startTime: '11:00', endTime: '12:00', status: 'scheduled', platform: 'Zoom', location: 'Virtual', meetingLink: 'https://zoom.us/j/5555555555', agenda: ['Product overview', 'Feature demo', 'Migration roadmap', 'Q&A session'], projectName: 'Customer Portal v3', recordingAvailable: false },
  { id: 'MTG-007', title: 'Weekly 1-on-1 — Sarah Chen', description: 'Weekly check-in to discuss progress, challenges, and career development.', organizer: 'James Wilson', organizerAvatar: '/avatars/emp6.jpg', participantIds: ['EMP-001', 'EMP-006'], participantNames: ['Sarah Chen', 'James Wilson'], participantAvatars: ['/avatars/emp1.jpg', '/avatars/emp6.jpg'], date: future(2), startTime: '15:00', endTime: '15:30', status: 'scheduled', platform: 'Google Meet', location: 'Virtual', meetingLink: 'https://meet.google.com/one-on-one', agenda: ['Review weekly progress', 'Discuss blockers', 'Career development goals'], recordingAvailable: false },
  { id: 'MTG-008', title: 'API Design Review', description: 'Review the rate limiting API design and approve the implementation approach.', organizer: 'Elena Rodriguez', organizerAvatar: '/avatars/emp5.jpg', participantIds: ['EMP-005', 'EMP-001', 'EMP-008'], participantNames: ['Elena Rodriguez', 'Sarah Chen', 'Thomas Müller'], participantAvatars: ['/avatars/emp5.jpg', '/avatars/emp1.jpg', '/avatars/emp2.jpg'], date: past(1), startTime: '14:00', endTime: '15:00', status: 'completed', platform: 'Teams', location: 'Virtual', meetingLink: 'https://teams.microsoft.com/l/meetup-join/def', agenda: ['Review token bucket design', 'Discuss client limits', 'Approve implementation'], projectName: 'Platform Infrastructure', recordingAvailable: true },
]

export const notices: Notice[] = [
  { id: 'NOT-001', title: 'Company Wide Q4 All-Hands Meeting', content: 'Our Q4 All-Hands meeting is scheduled for this Friday at 3:00 PM. We will cover Q3 results, Q4 roadmap, and team achievements. Attendance is mandatory for all employees.', category: 'event', priority: 'important', author: 'HR Department', postedAt: timeAgo(60), pinned: true, acknowledgments: ['EMP-001', 'EMP-002'] },
  { id: 'NOT-002', title: 'New VPN Security Policy Effective Monday', content: 'Starting Monday, all employees must connect through the corporate VPN before accessing internal tools. This is part of our enhanced security initiative.', category: 'policy', priority: 'urgent', author: 'IT Security', postedAt: timeAgo(180), pinned: true, acknowledgments: ['EMP-001', 'EMP-005', 'EMP-008'] },
  { id: 'NOT-003', title: 'WFH Equipment Upgrade Program', content: 'We are launching a work-from-home equipment upgrade program. Eligible employees can request up to $500 for ergonomic chairs, monitors, or accessories.', category: 'hr', priority: 'info', author: 'HR Department', postedAt: timeAgo(360), pinned: false, acknowledgments: ['EMP-003'] },
  { id: 'NOT-004', title: 'Scheduled System Maintenance — Saturday 2-6 AM', content: 'The monitoring platform will undergo scheduled maintenance this Saturday from 2:00 AM to 6:00 AM EST. During this time, screenshots, activity tracking, and reports will be temporarily unavailable.', category: 'system', priority: 'important', author: 'IT Operations', postedAt: timeAgo(480), pinned: false, acknowledgments: ['EMP-001', 'EMP-005'] },
  { id: 'NOT-005', title: 'New Time-Off Request Process', content: 'We have streamlined the time-off request process. All leave requests must now be submitted through the attendance module at least 5 business days in advance.', category: 'policy', priority: 'info', author: 'HR Department', postedAt: timeAgo(720), pinned: false, acknowledgments: [] },
  { id: 'NOT-006', title: 'Annual Performance Reviews Start Next Week', content: 'Annual performance reviews will begin next Monday. Please complete your self-assessment in the HR portal by Friday.', category: 'company', priority: 'important', author: 'HR Department', postedAt: timeAgo(1440), pinned: false, acknowledgments: ['EMP-001', 'EMP-003', 'EMP-005'] },
  { id: 'NOT-007', title: 'Team Building Virtual Event — Next Thursday', content: 'Join us for a virtual team building event next Thursday at 5 PM! We will have online trivia, virtual escape rooms, and prizes.', category: 'event', priority: 'info', author: 'HR Department', postedAt: timeAgo(2880), pinned: false, acknowledgments: [] },
]

export const chatConversations: ChatConversation[] = [
  { id: 'chat-1', type: 'direct', name: 'Sarah Chen', avatar: '/avatars/emp1.jpg', participantIds: ['EMP-001'], participantNames: ['Sarah Chen'], participantAvatars: ['/avatars/emp1.jpg'], online: true, lastMessageTime: timeAgo(3), unreadCount: 2, messages: [
    { id: 'm1', senderId: 'EMP-001', senderName: 'Sarah Chen', senderAvatar: '/avatars/emp1.jpg', text: 'Hey! Did you get a chance to review the OAuth PR?', timestamp: timeAgo(35), read: true },
    { id: 'm2', senderId: 'admin', senderName: 'Admin', senderAvatar: '', text: 'Yes, just looked at it. The token refresh logic looks solid.', timestamp: timeAgo(20), read: true },
    { id: 'm3', senderId: 'EMP-001', senderName: 'Sarah Chen', senderAvatar: '/avatars/emp1.jpg', text: 'Great! I also added 2FA support. Can you test the flow?', timestamp: timeAgo(5), read: false },
    { id: 'm4', senderId: 'EMP-001', senderName: 'Sarah Chen', senderAvatar: '/avatars/emp1.jpg', text: 'The staging link is in the PR description.', timestamp: timeAgo(3), read: false },
  ]},
  { id: 'chat-2', type: 'group', name: 'Engineering Team', avatar: '', participantIds: ['EMP-001', 'EMP-005', 'EMP-007', 'EMP-008'], participantNames: ['Sarah Chen', 'Elena Rodriguez', 'Aisha Mohammed', 'Thomas Müller'], participantAvatars: ['/avatars/emp1.jpg', '/avatars/emp5.jpg', '/avatars/emp1.jpg', '/avatars/emp2.jpg'], online: true, lastMessageTime: timeAgo(1), unreadCount: 5, messages: [
    { id: 'm5', senderId: 'EMP-008', senderName: 'Thomas Müller', senderAvatar: '/avatars/emp2.jpg', text: 'CI/CD pipeline is now live! All tests passing on staging.', timestamp: timeAgo(60), read: true },
    { id: 'm6', senderId: 'EMP-005', senderName: 'Elena Rodriguez', senderAvatar: '/avatars/emp5.jpg', text: 'Excellent! That unblocks the rate limiting work.', timestamp: timeAgo(45), read: true },
    { id: 'm7', senderId: 'EMP-001', senderName: 'Sarah Chen', senderAvatar: '/avatars/emp1.jpg', text: 'Should we schedule a deployment review for Friday?', timestamp: timeAgo(30), read: true },
    { id: 'm8', senderId: 'EMP-007', senderName: 'Aisha Mohammed', senderAvatar: '/avatars/emp1.jpg', text: 'I found a bug in the refund flow during regression testing.', timestamp: timeAgo(10), read: false },
    { id: 'm9', senderId: 'EMP-005', senderName: 'Elena Rodriguez', senderAvatar: '/avatars/emp5.jpg', text: 'Can you create a ticket for that? I will look into it today.', timestamp: timeAgo(1), read: false },
  ]},
  { id: 'chat-3', type: 'direct', name: 'James Wilson', avatar: '/avatars/emp6.jpg', participantIds: ['EMP-006'], participantNames: ['James Wilson'], participantAvatars: ['/avatars/emp6.jpg'], online: true, lastMessageTime: timeAgo(120), unreadCount: 0, messages: [
    { id: 'm10', senderId: 'admin', senderName: 'Admin', senderAvatar: '', text: 'James, can you prepare the client demo deck by Friday?', timestamp: timeAgo(180), read: true },
    { id: 'm11', senderId: 'EMP-006', senderName: 'James Wilson', senderAvatar: '/avatars/emp6.jpg', text: 'Sure, I will start on it today. Any specific features to highlight?', timestamp: timeAgo(120), read: true },
  ]},
  { id: 'chat-4', type: 'group', name: 'Design Sync', avatar: '', participantIds: ['EMP-003', 'EMP-001'], participantNames: ['Priya Patel', 'Sarah Chen'], participantAvatars: ['/avatars/emp3.jpg', '/avatars/emp1.jpg'], online: true, lastMessageTime: timeAgo(15), unreadCount: 1, messages: [
    { id: 'm12', senderId: 'EMP-003', senderName: 'Priya Patel', senderAvatar: '/avatars/emp3.jpg', text: 'I uploaded the new dashboard wireframes to Figma.', timestamp: timeAgo(40), read: true },
    { id: 'm13', senderId: 'EMP-001', senderName: 'Sarah Chen', senderAvatar: '/avatars/emp1.jpg', text: 'Looks great! The filter panel placement is much better now.', timestamp: timeAgo(20), read: true },
    { id: 'm14', senderId: 'EMP-003', senderName: 'Priya Patel', senderAvatar: '/avatars/emp3.jpg', text: 'Thanks! I will finalize the component library update this week.', timestamp: timeAgo(15), read: false },
  ]},
  { id: 'chat-5', type: 'direct', name: 'Marcus Johnson', avatar: '/avatars/emp2.jpg', participantIds: ['EMP-002'], participantNames: ['Marcus Johnson'], participantAvatars: ['/avatars/emp2.jpg'], online: true, lastMessageTime: timeAgo(240), unreadCount: 0, messages: [
    { id: 'm15', senderId: 'EMP-002', senderName: 'Marcus Johnson', senderAvatar: '/avatars/emp2.jpg', text: 'The Q3 reconciliation is 45% done. Found 3 discrepancies so far.', timestamp: timeAgo(240), read: true },
    { id: 'm16', senderId: 'admin', senderName: 'Admin', senderAvatar: '', text: 'Good progress. Flag anything over $500 and we will investigate together.', timestamp: timeAgo(230), read: true },
  ]},
  { id: 'chat-6', type: 'direct', name: 'David Kim', avatar: '/avatars/emp4.jpg', participantIds: ['EMP-004'], participantNames: ['David Kim'], participantAvatars: ['/avatars/emp4.jpg'], online: true, lastMessageTime: timeAgo(360), unreadCount: 0, messages: [
    { id: 'm17', senderId: 'admin', senderName: 'Admin', senderAvatar: '', text: 'David, how is the Q4 outreach going?', timestamp: timeAgo(400), read: true },
    { id: 'm18', senderId: 'EMP-004', senderName: 'David Kim', senderAvatar: '/avatars/emp4.jpg', text: 'Contacted 12 prospects, 3 demos scheduled. On track for the target.', timestamp: timeAgo(360), read: true },
  ]},
]
